# database configuration refer to https://www.keycloak.org/server/db ;
db=postgres
# Use container name for internal communication (containers on same network)
db-url-host=postgres
db-url-port=5432
db-url-database=keycloak
db-schema=public
db-username=${MACA_FIN_DATABASE_USERNAME}
db-password=${MACA_FIN_DATABASE_PASSWORD}
