# database configuration refer to https://www.keycloak.org/server/db ;
db=postgres
db-url-host=${MACA_FIN_DATABASE_HOST}
db-url-port=${MACA_FIN_DATABASE_PORT}
db-url-database=keycloak
db-schema=public
db-username=${MACA_FIN_DATABASE_USERNAME}
db-password=${MACA_FIN_DATABASE_PASSWORD}
# db-url=jdbc:postgresql://host.docker.internal:15432/keycloak
