quarkus:
  http:
    auth:
      basic: true
  datasource:
    db-kind: postgresql
    username: maca
    password: UxAYMurgKWd0rq6v
    jdbc:
      url: jdbc:postgresql://localhost:5432/demo
  hibernate-orm:
    database:
      generation: drop-and-create
