DROP TABLE IF EXISTS BACKEND.USER_ROLE;
CREATE TABLE BACKEND.USER_ROLE
(
    id         BIGINT PRIMARY KEY          NOT NULL,
    name       VARCHAR(128) UNIQUE         NOT NULL,
    level      INT                         NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE NULL     DEFAULT NULL,
    deleted    BOOLEAN                     NOT NULL DEFAULT FALSE
);

ALTER TABLE BACKEND.USER_ROLE
    OWNER TO MACA;

INSERT INTO BACKEND.USER_ROLE(id, name, level)
VALUES (1, 'ROOT', 1),
       (2, 'ADMIN', 10),
       (3, 'USER', 100),
       (4, 'GUEST', 1000);